version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:4003", "app:app"]
